Repository ugly-potato1/potato-API-server, pull requests merged in 2023-10, with the labels that each got.

#10 Feat: review 생성 API
  src/main/java/potato/potatoAPIserver/global/config/QueryDslConfig.java
  src/main/java/potato/potatoAPIserver/global/config/RedisConfig.java
  src/main/java/potato/potatoAPIserver/order/api/ReviewUpdateApi.java
  src/main/java/potato/potatoAPIserver/order/domain/Delivery.java
  src/main/java/potato/potatoAPIserver/order/domain/Review.java
  src/main/java/potato/potatoAPIserver/order/dto/request/ReviewCreateRequest.java
  src/main/java/potato/potatoAPIserver/order/repository/OrderProductRepository.java
  src/main/java/potato/potatoAPIserver/order/repository/OrderRepository.java
  src/main/java/potato/potatoAPIserver/order/repository/ProductRepository.java
  src/main/java/potato/potatoAPIserver/order/repository/ReviewRepository.java
  src/main/java/potato/potatoAPIserver/order/service/ReviewService.java
  src/main/java/potato/potatoAPIserver/security/CustomOAuth2UserService.java
  src/main/java/potato/potatoAPIserver/security/CustomPrincipal.java
  src/main/java/potato/potatoAPIserver/security/OAuth2AuthenticationSuccessHandler.java
Labels: Feat

#17 Feat: 공통 ResponseForm 구현
  src/main/java/potato/potatoAPIserver/common/CustomException.java
  src/main/java/potato/potatoAPIserver/common/GlobalExceptionHandler.java
  src/main/java/potato/potatoAPIserver/common/ResponseForm.java
  src/main/java/potato/potatoAPIserver/common/ResultCode.java
  src/main/java/potato/potatoAPIserver/common/StatusResponse.java
  src/main/java/potato/potatoAPIserver/order/api/ReviewUpdateApi.java
  src/main/java/potato/potatoAPIserver/order/dto/response/ReviewResponse.java
  src/main/java/potato/potatoAPIserver/order/service/ReviewService.java
  src/main/java/potato/potatoAPIserver/user/service/UserService.java
Labels: Feat, Refactor

#15 Feat: 리뷰 삭제 API 구현
  src/main/java/potato/potatoAPIserver/order/api/ReviewUpdateApi.java
  src/main/java/potato/potatoAPIserver/order/dto/request/ReviewCreateRequest.java
  src/main/java/potato/potatoAPIserver/order/repository/OrderProductRepository.java
  src/main/java/potato/potatoAPIserver/order/repository/OrderRepository.java
  src/main/java/potato/potatoAPIserver/order/repository/ReviewRepository.java
  src/main/java/potato/potatoAPIserver/order/service/ReviewService.java
Labels: Docs, Feat

#20 Feature: 배송 관련 ERD 수정
  build.gradle
  src/main/java/potato/potatoAPIserver/order/domain/Delivery.java
Labels: Feat, Fix

#21 Feat: aws s3 구축 및 저장 로직 구현
  build.gradle
  src/main/java/potato/potatoAPIserver/common/ResultCode.java
  src/main/java/potato/potatoAPIserver/file/FileService.java
  src/main/java/potato/potatoAPIserver/global/config/AwsS3Config.java
  src/main/java/potato/potatoAPIserver/order/api/ReviewUpdateApi.java
  src/main/java/potato/potatoAPIserver/order/dto/request/ReviewCreateRequest.java
  src/main/java/potato/potatoAPIserver/order/dto/response/ReviewResponse.java
  src/main/java/potato/potatoAPIserver/order/repository/ReviewImageRepository.java
  src/main/java/potato/potatoAPIserver/order/service/ReviewService.java
  src/main/resources/application.yml
Labels: Feat, Refactor

#23 Feat: 장바구니 테이블 추가하기
  src/main/java/potato/potatoAPIserver/order/api/ReviewUpdateApi.java
  src/main/java/potato/potatoAPIserver/order/domain/Cart.java
  src/main/java/potato/potatoAPIserver/order/domain/CartProduct.java
Labels: Feat, Fix
