Repository ugly-potato1/potato-API-server, pull requests merged in 2024-01, with the labels that each got.

#49 Feat 무중단 배포
  .github/workflows/cicd.yml
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  dokcer-compose.blue.yml
  dokcer-compose.green.yml
  nginx.blue.conf
  nginx.green.conf
  scripts/deploy.sh
Labels: Feat

#54 fix: docer 빌드,실행 오류
  .github/workflows/deploy.yml
  docker/Dockerfile
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  scripts/deploy.sh
Labels: Fix

#52 주소 CRUD
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/config/AwsS3Config.java
  src/main/java/potato/server/config/QueryDslConfig.java
  src/main/java/potato/server/config/RedisConfig.java
  src/main/java/potato/server/config/SecurityConfig.java
  src/main/java/potato/server/user/api/AddressAPI.java
  src/main/java/potato/server/user/domain/Address.java
  src/main/java/potato/server/user/domain/User.java
  src/main/java/potato/server/user/dto/request/CreateAddressRequest.java
  src/main/java/potato/server/user/dto/request/UpdateAddressRequest.java
  src/main/java/potato/server/user/dto/response/AddressResponse.java
  src/main/java/potato/server/user/repository/AddressRepository.java
  src/main/java/potato/server/user/repository/AddressRepositoryCustom.java
  src/main/java/potato/server/user/repository/AddressRepositoryImpl.java
  src/main/java/potato/server/user/service/AddressService.java
  src/main/java/potato/server/user/spec/DefaultAddr.java
  src/test/java/potato/server/address/AddressAPITest.java
  src/test/java/potato/server/common/WithMockCustomMemberSecurityContextFactory.java
Labels: Feat, Test

#57 feat: product
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/product/api/ProductApi.java
  src/main/java/potato/server/product/domain/Category.java
  src/main/java/potato/server/product/domain/Product.java
  src/main/java/potato/server/product/domain/Wishlist.java
  src/main/java/potato/server/product/dto/request/ProductCreateRequest.java
  src/main/java/potato/server/product/dto/request/ProductUpdateRequest.java
  src/main/java/potato/server/product/dto/response/ProductResponse.java
  src/main/java/potato/server/product/repository/CategoryRepository.java
  src/main/java/potato/server/product/repository/ProductRepository.java
  src/main/java/potato/server/product/repository/ProductRepositoryCustom.java
  src/main/java/potato/server/product/repository/ProductRepositoryImpl.java
  src/main/java/potato/server/product/repository/WishlistRepository.java
  src/main/java/potato/server/product/service/CategoryService.java
  src/main/java/potato/server/product/service/ProductService.java
  src/main/java/potato/server/product/service/WishlistService.java
Labels: Feat

#56 Fix: 배포 타임아웃 시간 늘리기
  appspec.yml
Labels: Fix

#63 Feat: 리뷰 이미지 생성, 삭제
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/file/FileCreateRequest.java
  src/main/java/potato/server/file/FileService.java
  src/main/java/potato/server/review/api/ReviewImageUpdateApi.java
  src/main/java/potato/server/review/api/ReviewUpdateApi.java
  src/main/java/potato/server/review/domain/Review.java
  src/main/java/potato/server/review/domain/ReviewImage.java
  src/main/java/potato/server/review/dto/request/ReviewCreateRequest.java
  src/main/java/potato/server/review/dto/request/ReviewImageDeleteRequest.java
  src/main/java/potato/server/review/dto/response/ReviewImageCreateResponse.java
  src/main/java/potato/server/review/dto/response/ReviewResponse.java
  src/main/java/potato/server/review/repository/ReviewImageRepository.java
  src/main/java/potato/server/review/repository/ReviewRepository.java
  src/main/java/potato/server/review/service/ReiewImageService.java
  src/main/java/potato/server/review/service/ReviewService.java
Labels: Feat, Refactor

#64 Feat: 마이 페이지 API
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/config/AsyncConfig.java
  src/main/java/potato/server/config/MailConfig.java
  src/main/java/potato/server/mail/AuthMailService.java
  src/main/java/potato/server/mail/MailController.java
  src/main/java/potato/server/mail/dto/AuthNumberResponse.java
  src/main/java/potato/server/mail/dto/SendMailRequest.java
  src/main/java/potato/server/mail/util/RandomGenerator.java
  src/main/java/potato/server/mail/util/SendMailService.java
  src/main/java/potato/server/redis/RedisUtil.java
  src/main/java/potato/server/user/api/ProfileApi.java
  src/main/java/potato/server/user/domain/User.java
  src/main/java/potato/server/user/dto/request/UpdateEmailRequest.java
  src/main/java/potato/server/user/dto/request/UpdatePhoneNumberRequest.java
  src/main/java/potato/server/user/dto/request/UpdateProfileImageRequest.java
  src/main/java/potato/server/user/dto/response/ProfileImageUpdateResponse.java
  src/main/java/potato/server/user/dto/response/UserProfileResponse.java
  src/main/java/potato/server/user/service/ProfileService.java
  src/main/java/potato/server/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/potato/PotatoApiServerApplicationTests.java
  src/test/java/potato/server/address/AddressAPITest.java
  src/test/java/potato/server/mail/MailApiTest.java
  src/test/java/potato/server/user/profile/ProfileApiTest.java
Labels: Feat, Test

#66 Update ProductUpdateRequest.java
  src/main/java/potato/server/product/dto/request/ProductUpdateRequest.java
Labels: Feat

#70 [Feat] 커뮤니티 기능 구현
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/community/api/CommentController.java
  src/main/java/potato/server/community/api/PostController.java
  src/main/java/potato/server/community/domain/Comment.java
  src/main/java/potato/server/community/domain/Post.java
  src/main/java/potato/server/community/dto/request/CommentRequest.java
  src/main/java/potato/server/community/dto/request/CommentUpdateRequest.java
  src/main/java/potato/server/community/dto/request/PostRequest.java
  src/main/java/potato/server/community/dto/response/CommentCreateResponse.java
  src/main/java/potato/server/community/dto/response/CommentPageResponse.java
  src/main/java/potato/server/community/dto/response/CommentResponse.java
  src/main/java/potato/server/community/dto/response/PostCreateResponse.java
  src/main/java/potato/server/community/dto/response/PostPageResponse.java
  src/main/java/potato/server/community/dto/response/PostResponse.java
  src/main/java/potato/server/community/repository/CommentRepository.java
  src/main/java/potato/server/community/repository/PostRepository.java
  src/main/java/potato/server/community/service/CommentReadService.java
  src/main/java/potato/server/community/service/CommentWriteService.java
  src/main/java/potato/server/community/service/PostReadService.java
  src/main/java/potato/server/community/service/PostWriteService.java
  src/main/java/potato/server/config/SecurityConfig.java
  src/test/java/potato/PotatoApiServerApplicationTests.java
  src/test/java/potato/server/address/AddressAPITest.java
  src/test/java/potato/server/community/api/CommentControllerTest.java
  src/test/java/potato/server/community/api/PostControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/data.sql
Labels: Feat, Test

#73 Feat: 결제 API
  build.gradle
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/order/api/PaymentApi.java
  src/main/java/potato/server/order/domain/Order.java
  src/main/java/potato/server/order/domain/Payment.java
  src/main/java/potato/server/order/dto/ImpRefundDTO.java
  src/main/java/potato/server/order/dto/request/PaymentCancleRequest.java
  src/main/java/potato/server/order/dto/request/PaymentCompleteRequest.java
  src/main/java/potato/server/order/dto/request/PaymentPreValidateRequest.java
  src/main/java/potato/server/order/dto/response/PaymentCompleteResponse.java
  src/main/java/potato/server/order/repository/OrderRepository.java
  src/main/java/potato/server/order/repository/PaymentRepository.java
  src/main/java/potato/server/order/service/ImpPaymentService.java
  src/main/java/potato/server/order/service/PaymentService.java
  src/main/java/potato/server/security/oauth/KakaoOAuth2UserAttribute.java
  src/main/java/potato/server/security/oauth/NaverOAuth2UserAttribute.java
  src/main/resources/application.yml
  src/test/java/potato/server/order/payment/PaymentApiTest.java
Labels: Feat, Test

#67 Feat 특정 상품 리뷰 조회
  src/main/java/potato/server/review/api/ReviewGetApi.java
  src/main/java/potato/server/review/api/ReviewUpdateApi.java
  src/main/java/potato/server/review/domain/Review.java
  src/main/java/potato/server/review/dto/request/AllReviewByProductGetRequest.java
  src/main/java/potato/server/review/dto/request/ReviewCreateRequest.java
  src/main/java/potato/server/review/dto/response/ReviewCreateResponse.java
  src/main/java/potato/server/review/dto/response/ReviewGetResponse.java
  src/main/java/potato/server/review/repository/ReviewRepository.java
  src/main/java/potato/server/review/service/ReviewGetService.java
  src/main/java/potato/server/review/service/ReviewService.java
  src/main/java/potato/server/review/spec/ChoicedExperience.java
  src/test/java/potato/server/review/ReviewGetApiTest.java
Labels: Feat

#77 JpaAuditing 설정 추가
  src/main/java/potato/server/common/ResultCode.java
  src/main/java/potato/server/config/JpaConfig.java
Labels: Chore, Fix

#79 Mysql 연결하기
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/potato/server/order/api/OrderApi.java
  src/main/resources/application.yml
  src/test/java/potato/server/mail/MailApiTest.java
  src/test/java/potato/server/order/payment/PaymentApiTest.java
  src/test/java/potato/server/review/ReviewGetApiTest.java
  src/test/java/potato/server/user/profile/ProfileApiTest.java
  src/test/resources/application-test.yml
Labels: Feat

#83 Deploy 파일 수정
  .github/workflows/deploy.yml
Labels: Feat, Fix
